# Generated by Django 3.0.7 on 2020-06-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='checker',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='problems',
        ),
        migrations.AddField(
            model_name='problem',
            name='test_case_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.TestCaseGroup'),
        ),
    ]
