# Generated by Django 2.2.6 on 2019-10-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191027_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseresult',
            name='stdout',
            field=models.TextField(blank=True, null=True),
        ),
    ]
