# Generated by Django 3.0.7 on 2020-06-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200607_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='round',
        ),
        migrations.AddField(
            model_name='problem',
            name='rounds',
            field=models.ManyToManyField(to='dashboard.Round'),
        ),
    ]
