# Generated by Django 3.1.3 on 2020-11-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200607_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseresult',
            name='runtime',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
