# Generated by Django 2.2.6 on 2019-10-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191027_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseresult',
            name='stderr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
