# Generated by Django 2.2.6 on 2019-10-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_testcaseresult_stderr'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='cpp_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='java_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='python_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
