# Generated by Django 4.0.4 on 2022-05-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_testcaseresult_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
