# Generated by Django 2.2.6 on 2019-11-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20191031_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='cpp_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='java_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='python_time',
            field=models.FloatField(),
        ),
    ]
