# Generated by Django 2.2.6 on 2019-11-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20191101_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.BinaryField(),
        ),
    ]
