# Generated by Django 2.2.6 on 2019-11-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20191102_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default='A Team'),
            preserve_default=False,
        ),
    ]
