# Generated by Django 2.2.6 on 2020-06-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20191102_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eligible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.TextField(blank=True),
        ),
    ]
